### ISSUE TITLE
Flaky selection of the last problem in the list

### ISSUE THREAD

**Issue by kgashok** [cloudcoderdotorg/CloudCoder#74]
In the "Problems in CCDemo - CloudCoder demo course" page, selection of the last problem in the list is flaky (sometimes I am able to select it, but can't explain exactly when). 
For now, I just add a "dummy" problem, and that way, I am able to select the last but one and then go on to edit it. 

![cloudcoder issue](https://f.cloud.github.com/assets/2399010/1423242/b090abfa-4007-11e3-9587-408c9b4ab866.PNG)

**Comment by daveho** [comment]
I don't think I was able to reproduce this - please open a new issue if it recurs.
