### ISSUE TITLE
C/C++ - Can't use "iostream"

### ISSUE THREAD

**Issue by dckoma** [cloudcoderdotorg/CloudCoder#90]
I have succesfully installed the webapp/builder and everything works fine.
But when I want to include the iostream lib there is the error note "Error compiling submission" after I press the Submit! button. 
"stdio.h" works fine.

**Comment by katieirenec** [comment]
Hi @dckoma! 
I was able to #include <iostream> without issue on my install of CloudCoder, for both CPLUSPLUS_FUNCTION and CPLUSCPLUS_PROGRAM. Are you sure you're using the CPLUSPLUS_* options instead of C_FUNCTION or C_PROGRAM?

Let me know and if you have any other info I'm happy to try to help.

**Comment by dckoma** [comment]
Hello @katieirenec  
Yes I used the CPLUSPLUS_FUNCTION/PROGRAM. Don't know why it doesn't work.
I set up a new virtual machine and however it works now.

Thank's anyways :)

**Comment by katieirenec** [comment]
Awesome! Glad it works :)
